---

# Main tasks file for exim4 role

- name: 'INIT | Manage variables to use for our target'
  import_tasks: "{{ role_path }}/tasks/manage_variables.yml"
  tags:
    - 'role::exim4'
    - 'role::exim4::init'
